/**
 * LANDVAULT AI — demo uploaded documents.
 *
 * Hand-authored SAMPLE DocumentRecord rows that the documents list and dashboard
 * render in demo / no-backend mode. They mirror the real engine output served by
 * the backend (`documentsApi.list` → GET /api/documents) and must always satisfy
 * the `DocumentRecord` contract in `@/types`.
 *
 * Every `id` below cross-references the demo data already used in `@/lib/demo-data`
 * (audit / conflicts / records) so the document rows line up against the same
 * underlying records. Statuses deliberately span every `DocumentStatus` value
 * (QUEUED, PREPROCESSING, OCR, EXTRACTION, VALIDATION, REVIEW_REQUIRED,
 * COMPLETED, FAILED) so the DocumentsPage status cells and dashboard document
 * panel have representative data to render, and `ocrConfidence` exercises the
 * confidence tiers shown by DocumentsPanel (`> 0.85` success, else warning).
 */

import type { DocumentRecord } from '@/types'

/** Demo timestamp used so sample data renders deterministically. */
const DEMO_TIMESTAMP = '2025-08-15T09:30:00.000Z'

/** Demo documents spanning every pipeline status and document type. */
export const DEMO_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'DOC-PATTA-001',
    referenceNo: 'REC-124/2A-PATTA',
    filename: 'REC-124_2A-PATTA.pdf',
    documentType: 'PATTA',
    language: ['ta', 'en'],
    district: 'Tiruchirappalli',
    taluk: 'Srirangam',
    village: 'Srirangam',
    pageCount: 2,
    fileSizeBytes: 1048576,
    status: 'COMPLETED',
    progress: 100,
    uploadedAt: DEMO_TIMESTAMP,
    uploadedBy: 'Anjali Sharma',
    ocrConfidence: 0.91,
  },
  {
    id: 'DOC-CHITTA-002',
    referenceNo: 'REC-124/2A-CHITTA',
    filename: 'REC-124_2A-CHITTA.pdf',
    documentType: 'CHITTA',
    language: ['ta', 'en'],
    district: 'Tiruchirappalli',
    taluk: 'Srirangam',
    village: 'Srirangam',
    pageCount: 1,
    fileSizeBytes: 524288,
    status: 'COMPLETED',
    progress: 100,
    uploadedAt: '2025-08-15T10:12:00.000Z',
    uploadedBy: 'Ravi Kumar',
    ocrConfidence: 0.88,
  },
  {
    id: 'DOC-FMB-002',
    referenceNo: 'REC-124/2A-FMB',
    filename: 'REC-124_2A-FMB.pdf',
    documentType: 'FMB',
    language: ['en'],
    district: 'Tiruchirappalli',
    taluk: 'Srirangam',
    village: 'Srirangam',
    pageCount: 2,
    fileSizeBytes: 734003,
    status: 'COMPLETED',
    progress: 100,
    uploadedAt: '2025-08-15T10:12:00.000Z',
    uploadedBy: 'Ravi Kumar',
    ocrConfidence: 0.95,
    previewUrl: '/demo/previews/fmb-002.png',
  },
  {
    id: 'DOC-FMB-005',
    referenceNo: 'REC-045_1C-FMB',
    filename: 'REC-045_1C-FMB.pdf',
    documentType: 'FMB',
    language: ['ta', 'en'],
    district: 'Perambalur',
    taluk: 'Perambalur',
    village: 'Perambalur',
    pageCount: 1,
    fileSizeBytes: 524288,
    status: 'COMPLETED',
    progress: 100,
    uploadedAt: '2025-08-19T15:40:00.000Z',
    uploadedBy: 'Kavitha Ramesh',
    ocrConfidence: 0.85,
  },
  {
    id: 'DOC-REG-003',
    referenceNo: 'REC-091/3B-REG',
    filename: 'REC-091_3B-REG.pdf',
    documentType: 'SALE_REGISTRATION',
    language: ['en'],
    district: 'Tiruppur',
    taluk: 'Tiruppur',
    village: 'Tiruppur',
    pageCount: 3,
    fileSizeBytes: 1572864,
    status: 'REVIEW_REQUIRED',
    progress: 100,
    uploadedAt: '2025-08-15T11:45:00.000Z',
    uploadedBy: 'Ravi Kumar',
    ocrConfidence: 0.45,
  },
  {
    id: 'DOC-OCR-004',
    referenceNo: 'REC-055/1A-PATTA',
    filename: 'REC-055_1A-PATTA.pdf',
    documentType: 'PATTA',
    language: ['ta', 'en'],
    district: 'Nagapattinam',
    taluk: 'Nagapattinam',
    village: 'Kilvanthai',
    pageCount: 2,
    fileSizeBytes: 943718,
    status: 'REVIEW_REQUIRED',
    progress: 100,
    uploadedAt: '2025-08-16T09:15:00.000Z',
    uploadedBy: 'Priya Nair',
    ocrConfidence: 0.42,
  },
  {
    id: 'DOC-AREG-006',
    referenceNo: 'REC-033/2A-AREG',
    filename: 'REC-033_2A-AREG.pdf',
    documentType: 'RECORD_OF_RIGHTS',
    language: ['ta'],
    district: 'Salem',
    taluk: 'Mettur',
    village: 'Mettur',
    pageCount: 3,
    fileSizeBytes: 1258291,
    status: 'COMPLETED',
    progress: 100,
    uploadedAt: '2025-08-15T14:20:00.000Z',
    uploadedBy: 'Anjali Sharma',
    ocrConfidence: 0.89,
    previewUrl: '/demo/previews/arear-006.png',
  },
  {
    id: 'DOC-GIS-005',
    referenceNo: 'REC-078/4C-GIS',
    filename: 'REC-078_4C-GIS.pdf',
    documentType: 'SURVEY_RECORD',
    language: ['en'],
    district: 'Tirunelveli',
    taluk: 'Tirunelveli',
    village: 'Palayamkottai',
    pageCount: 1,
    fileSizeBytes: 314572,
    status: 'COMPLETED',
    progress: 100,
    uploadedAt: '2025-08-18T11:05:00.000Z',
    uploadedBy: 'Priya Nair',
    ocrConfidence: null,
  },
  {
    id: 'DOC-CHITTA-007',
    referenceNo: 'REC-112/5B-CHITTA',
    filename: 'REC-112_5B-CHITTA.pdf',
    documentType: 'CHITTA',
    language: ['ta', 'en'],
    district: 'Tiruppur',
    taluk: 'Tiruppur',
    village: 'Tiruppur',
    pageCount: 2,
    fileSizeBytes: 1153433,
    status: 'COMPLETED',
    progress: 100,
    uploadedAt: '2025-08-21T16:30:00.000Z',
    uploadedBy: 'Priya Nair',
    ocrConfidence: 0.9,
  },
  {
    id: 'DOC-REG-008',
    referenceNo: 'REC-045/1C-REG',
    filename: 'REC-045_1C-REG.pdf',
    documentType: 'SALE_REGISTRATION',
    language: ['en'],
    district: 'Perambalur',
    taluk: 'Perambalur',
    village: 'Perambalur',
    pageCount: 2,
    fileSizeBytes: 838860,
    status: 'COMPLETED',
    progress: 100,
    uploadedAt: '2025-08-19T08:20:00.000Z',
    uploadedBy: 'Priya Nair',
    ocrConfidence: 0.72,
  },
]