/**
 * LANDVAULT AI — demo land records.
 *
 * Hand-authored SAMPLE LandRecord rows that the verification queue, record
 * workspace and dashboard render in demo / no-backend mode. They mirror the
 * real engine output served by the backend (`recordsApi.list` → GET /api/records,
 * sourced from the Bhu-Naksha cadastral index cross-referenced against Patta,
 * Chitta, A-Register, Adangal and Registration extracts) and must always satisfy
 * the `LandRecord` contract in `@/types`.
 *
 * Every `id` below cross-references the demo data already used in `@/lib/demo-data`
 * (audit / conflicts / validation / parcels) so the cross-source conflicts, audit
 * trail and GIS boundaries all line up against the same underlying records. Statuses
 * span every `RecordStatus` value (DRAFT, EXTRACTED, IN_REVIEW, VERIFIED, CONFLICT)
 * and the `fields[].confidence` values exercise the confidence tiers used by
 * VerificationQueuePage's `flaggedFieldsOf` filter.
 */

import type { LandRecord } from '@/types'

/** Demo timestamp used so sample data renders deterministically. */
const DEMO_TIMESTAMP = '2025-08-15T09:30:00.000Z'

/** Demo land records spanning Tamil Nadu, with cross-source conflicts to resolve. */
export const DEMO_LAND_RECORDS: LandRecord[] = [
  {
    id: 'REC-124/2A-PATTA',
    recordNumber: 'REC-124/2A',
    documentId: 'DOC-PATTA-001',
    surveyNumber: '124/2A',
    subdivisionNumber: '2A',
    khataNumber: 'K-124-B',
    ownerName: 'R. Rajesh',
    ownerNameTamil: 'ஆர். ராஜேஷ்',
    coOwners: [],
    area: 2.5,
    areaUnit: 'Acres',
    village: 'Srirangam',
    taluk: 'Tiruchirappalli',
    district: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    landType: 'Dry land',
    documentType: 'PATTA',
    documentNumber: 'REG-124/2A/2010',
    registrationDate: '2010-03-18',
    status: 'CONFLICT',
    verifyConfidence: 0.58,
    fields: [
      {
        key: 'ownerName',
        label: 'Owner Name',
        value: 'R. Rajesh',
        confidence: 0.58,
        sourcePage: 1,
        sourceText: 'R. Rajesh, S/o Ramesh',
        sourceBbox: { x: 42, y: 128, w: 210, h: 16 },
        method: 'OCR_HEURISTIC',
        status: 'REVIEW_REQUIRED',
      },
      {
        key: 'surveyNumber',
        label: 'Survey Number',
        value: '124/2A',
        confidence: 0.95,
        sourcePage: 2,
        sourceText: 'Survey No. 124/2A',
        sourceBbox: { x: 42, y: 210, w: 90, h: 14 },
        method: 'PATTERN',
        status: 'ACCEPTED',
      },
      {
        key: 'area',
        label: 'Area',
        value: '2.50 acres',
        confidence: 0.92,
        sourcePage: 2,
        sourceText: 'Extent 2.50 acres',
        sourceBbox: { x: 42, y: 240, w: 88, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'khataNumber',
        label: 'Khata Number',
        value: 'K-124-B',
        confidence: 0.78,
        sourcePage: 3,
        sourceText: 'Khata No. K-124-B',
        sourceBbox: { x: 42, y: 302, w: 86, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
    ],
    createdAt: DEMO_TIMESTAMP,
    updatedAt: '2025-08-18T14:20:00.000Z',
  },
  {
    id: 'REC-045/1C-PATTA',
    recordNumber: 'REC-045/1C',
    documentId: 'DOC-FMB-005',
    surveyNumber: '045/1C',
    subdivisionNumber: '1C',
    khataNumber: 'K-045-C',
    ownerName: 'P. Senthil Kumar',
    coOwners: [],
    area: 1.85,
    areaUnit: 'Acres',
    village: 'Perambalur',
    taluk: 'Perambalur',
    district: 'Perambalur',
    state: 'Tamil Nadu',
    landType: 'Irrigated land',
    documentType: 'FMB',
    documentNumber: null,
    registrationDate: '2010-06-15',
    status: 'IN_REVIEW',
    verifyConfidence: 0.6,
    fields: [
      {
        key: 'ownerName',
        label: 'Owner Name',
        value: 'P. Senthil Kumar',
        confidence: 0.6,
        sourcePage: 1,
        sourceText: 'P. Senthil Kumar, S/o Palani',
        sourceBbox: { x: 42, y: 120, w: 200, h: 16 },
        method: 'OCR_HEURISTIC',
        status: 'REVIEW_REQUIRED',
      },
      {
        key: 'surveyNumber',
        label: 'Survey Number',
        value: '045/1C',
        confidence: 0.97,
        sourcePage: 2,
        sourceText: '045/1C',
        sourceBbox: { x: 42, y: 204, w: 70, h: 14 },
        method: 'PATTERN',
        status: 'ACCEPTED',
      },
      {
        key: 'area',
        label: 'Area',
        value: '1.85 acres',
        confidence: 0.91,
        sourcePage: 1,
        sourceText: '1.85 acres',
        sourceBbox: { x: 300, y: 120, w: 72, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'registrationDate',
        label: 'Registration Date',
        value: '15-06-2010',
        confidence: 0.84,
        sourcePage: 4,
        sourceText: 'Dated 15-06-2010',
        sourceBbox: { x: 42, y: 400, w: 110, h: 14 },
        method: 'PATTERN',
        status: 'ACCEPTED',
      },
    ],
    createdAt: DEMO_TIMESTAMP,
    updatedAt: '2025-08-16T14:30:00.000Z',
  },
  {
    id: 'REC-078/4C-PATTA',
    recordNumber: 'REC-078/4C',
    documentId: 'DOC-GIS-005',
    surveyNumber: '078/4C',
    subdivisionNumber: '4C',
    khataNumber: 'K-078-D',
    ownerName: 'R. Meena',
    coOwners: ['S. Parthasarathy'],
    area: 1.85,
    areaUnit: 'Acres',
    village: 'Palayamkottai',
    taluk: 'Tirunelveli',
    district: 'Tirunelveli',
    state: 'Tamil Nadu',
    landType: 'Garden land',
    documentType: 'PATTA',
    documentNumber: 'REG-078/4C/2012',
    registrationDate: null,
    status: 'CONFLICT',
    verifyConfidence: 0.52,
    fields: [
      {
        key: 'ownerName',
        label: 'Owner Name',
        value: 'R. Meena',
        confidence: 0.9,
        sourcePage: 1,
        sourceText: 'R. Meena, W/o Ramesh',
        sourceBbox: { x: 42, y: 110, w: 150, h: 16 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'surveyNumber',
        label: 'Survey Number',
        value: '078/4C',
        confidence: 0.94,
        sourcePage: 2,
        sourceText: 'Survey No. 078/4C',
        sourceBbox: { x: 42, y: 220, w: 100, h: 14 },
        method: 'PATTERN',
        status: 'ACCEPTED',
      },
      {
        key: 'area',
        label: 'Area',
        value: '1.85 acres',
        confidence: 0.92,
        sourcePage: 2,
        sourceText: 'Extent 1.85 acres',
        sourceBbox: { x: 42, y: 252, w: 88, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'boundary',
        label: 'Boundary',
        value: 'See FMB sketch',
        confidence: 0.66,
        sourcePage: 3,
        sourceText: 'North: per Gomedapalle, South: per tank bed',
        sourceBbox: { x: 42, y: 310, w: 320, h: 14 },
        method: 'TABLE_PARSING',
        status: 'REVIEW_REQUIRED',
      },
    ],
    createdAt: DEMO_TIMESTAMP,
    updatedAt: '2025-08-18T11:05:00.000Z',
  },
  {
    id: 'REC-055/1A-PATTA',
    recordNumber: 'REC-055/1A',
    documentId: 'DOC-OCR-004',
    surveyNumber: '055/1A',
    subdivisionNumber: '1A',
    khataNumber: 'K-055-A',
    ownerName: 'M. Kathiravan',
    coOwners: [],
    area: 3.1,
    areaUnit: 'Acres',
    village: 'Kilvanthai',
    taluk: 'Nagapattinam',
    district: 'Nagapattinam',
    state: 'Tamil Nadu',
    landType: 'Permanently irrigated land',
    documentType: 'PATTA',
    documentNumber: 'REG-055/1A/2015',
    registrationDate: '2015-11-03',
    status: 'VERIFIED',
    verifyConfidence: 0.78,
    fields: [
      {
        key: 'ownerName',
        label: 'Owner Name',
        value: 'M. Kathiravan',
        confidence: 0.42,
        sourcePage: 1,
        sourceText: 'M. Kathiravan [confidence: 0.42]',
        sourceBbox: { x: 42, y: 128, w: 190, h: 16 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'surveyNumber',
        label: 'Survey Number',
        value: '055/1A',
        confidence: 0.96,
        sourcePage: 2,
        sourceText: '055/1A',
        sourceBbox: { x: 42, y: 212, w: 66, h: 14 },
        method: 'PATTERN',
        status: 'ACCEPTED',
      },
      {
        key: 'area',
        label: 'Area',
        value: '3.10 acres',
        confidence: 0.93,
        sourcePage: 2,
        sourceText: '3.10 acres',
        sourceBbox: { x: 42, y: 244, w: 76, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'landType',
        label: 'Land Type',
        value: 'Permanently irrigated land',
        confidence: 0.81,
        sourcePage: 3,
        sourceText: 'Permanently irrigated',
        sourceBbox: { x: 42, y: 290, w: 170, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
    ],
    createdAt: DEMO_TIMESTAMP,
        updatedAt: '2025-08-16T09:15:00.000Z',
  },
  {
    id: 'REC-091/3B-PATTA',
    recordNumber: 'REC-091/3B',
    documentId: 'DOC-REG-003',
    surveyNumber: '091/3B',
    subdivisionNumber: '3B',
    khataNumber: 'K-091-B',
    ownerName: 'P. Senthilkumar',
    coOwners: [],
    area: 0.95,
    areaUnit: 'Acres',
    village: 'Tiruppur',
    taluk: 'Tiruppur',
    district: 'Tiruppur',
    state: 'Tamil Nadu',
    landType: 'Dry land',
    documentType: 'SALE_REGISTRATION',
    documentNumber: 'REG-091/3B/2023',
    registrationDate: '2023-02-28',
    status: 'EXTRACTED',
    verifyConfidence: 0.45,
    fields: [
      {
        key: 'ownerName',
        label: 'Owner Name',
        value: 'P. Senthilkumar',
        confidence: 0.88,
        sourcePage: 3,
        sourceText: 'P. Senthilkumar, S/o Muthusamy',
        sourceBbox: { x: 42, y: 150, w: 210, h: 16 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'surveyNumber',
        label: 'Survey Number',
        value: '091/3B',
        confidence: 0.97,
        sourcePage: 2,
        sourceText: '091/3B',
        sourceBbox: { x: 42, y: 200, w: 70, h: 14 },
        method: 'PATTERN',
        status: 'ACCEPTED',
      },
      {
        key: 'area',
        label: 'Area',
        value: '0.95 acres',
        confidence: 0.89,
        sourcePage: 2,
        sourceText: 'Extent 0.95 acres',
        sourceBbox: { x: 42, y: 232, w: 82, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'registrationDate',
        label: 'Registration Date',
        value: '30-02-2023',
        confidence: 0.35,
        sourcePage: 1,
        sourceText: 'Dated 30-02-2023',
        sourceBbox: { x: 42, y: 110, w: 112, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'CORRECTED',
      },
    ],
    createdAt: DEMO_TIMESTAMP,
    updatedAt: '2025-08-16T10:30:00.000Z',
  },
  {
    id: 'REC-033/2A-PATTA',
    recordNumber: 'REC-033/2A',
    documentId: 'DOC-AREG-006',
    surveyNumber: '033/2A',
    subdivisionNumber: '2A',
    khataNumber: 'K-033-A',
    ownerName: 'S. Meena',
    coOwners: ['K. Parthasarathy'],
    area: 2.2,
    areaUnit: 'Acres',
    village: 'Mettur',
    taluk: 'Salem',
    district: 'Salem',
    state: 'Tamil Nadu',
    landType: 'Dry land',
    documentType: 'RECORD_OF_RIGHTS',
    documentNumber: null,
    registrationDate: null,
    status: 'CONFLICT',
    verifyConfidence: 0.67,
    fields: [
      {
        key: 'ownerName',
        label: 'Owner Name',
        value: 'S. Meena',
        confidence: 0.91,
        sourcePage: 1,
        sourceText: 'S. Meena, D/o Sankaran',
        sourceBbox: { x: 42, y: 124, w: 150, h: 16 },
        method: 'OCR_HEURISTIC',
        status: 'ACCEPTED',
      },
      {
        key: 'surveyNumber',
        label: 'Survey Number',
        value: '033/2A',
        confidence: 0.96,
        sourcePage: 2,
        sourceText: 'Survey No. 033/2A',
        sourceBbox: { x: 42, y: 218, w: 100, h: 14 },
        method: 'PATTERN',
        status: 'ACCEPTED',
      },
      {
        key: 'area',
        label: 'Area',
        value: '2.20 acres',
        confidence: 0.9,
        sourcePage: 2,
        sourceText: '2.20 acres',
        sourceBbox: { x: 42, y: 250, w: 76, h: 14 },
        method: 'OCR_HEURISTIC',
        status: 'REVIEW_REQUIRED',
      },
      {
        key: 'khataNumber',
        label: 'Khata Number',
        value: null,
        confidence: null,
        sourcePage: null,
        sourceText: null,
        sourceBbox: null,
        method: 'NER',
        status: 'REVIEW_REQUIRED',
      },
    ],
    createdAt: DEMO_TIMESTAMP,
    updatedAt: '2025-08-17T15:40:00.000Z',
  },
]
