"""LANDVAULT AI API — FastAPI backend serving the real-data database.

Routers live in `app/routers/`; each resource module owns its endpoints. Data
comes from the tables defined in models.py (fed by `scripts/init_db.py`, seeded
from SIH26018_REAL_DATA). No synthetic values are generated by default: endpoints
return empty results until real data has been ingested.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from .config import settings
from .routers import audit, auth, conflicts, documents, parcels, records, stats

app = FastAPI(title=settings.app_name)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(auth.router)
app.include_router(stats.router)
app.include_router(documents.router)
app.include_router(records.router)
app.include_router(conflicts.router)
app.include_router(audit.audit_router)
app.include_router(audit.activity_router)
app.include_router(parcels.router)


@app.get("/api/health")
def health():
    return {"status": "ok"}