"""LANDVAULT AI API — FastAPI backend serving the real-data database.

Routers live in `app/routers/`; each resource module owns its endpoints. Data
comes from the tables defined in models.py (fed by `scripts/init_db.py`, seeded
from SIH26018_REAL_DATA). No synthetic values are generated by default: endpoints
return empty results until real data has been ingested.

Security: every API response carries hardened headers (nosniff, DENY framing,
strict referrer policy, API-locked CSP, no-store) and HSTS is added in
production. See the README "Security" section for the full control list.
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware

from .config import settings
from .database import Base, engine
from .routers import audit, auth, conflicts, documents, parcels, records, stats

# Hardened defaults for every API response. `Cache-Control: no-store` keeps
# authenticated government data out of shared caches; `Content-Security-Policy`
# is locked down because this service serves JSON, not HTML.
SECURITY_HEADERS = {
    "X-Content-Type-Options": "nosniff",
    "X-Frame-Options": "DENY",
    "Referrer-Policy": "strict-origin-when-cross-origin",
    "Permissions-Policy": "camera=(self), microphone=(), geolocation=(), payment=()",
    "Content-Security-Policy": "default-src 'none'; frame-ancestors 'none'; form-action 'self'",
    "Cross-Origin-Opener-Policy": "same-origin",
    "Cache-Control": "no-store",
}


@asynccontextmanager
async def lifespan(_: FastAPI):
    # Idempotent — ensures newly introduced tables (e.g. session_tokens) exist on
    # databases initialised by an earlier version. Schema creation + seeding still
    # belong to scripts/init_db.py.
    Base.metadata.create_all(bind=engine)
    yield


app = FastAPI(title=settings.app_name, lifespan=lifespan)
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def add_security_headers(request: Request, call_next):
    response = await call_next(request)
    response.headers.update(SECURITY_HEADERS)
    if settings.environment == "production":
        # Only meaningful over HTTPS — emitted when deployed in production mode.
        response.headers.setdefault("Strict-Transport-Security", "max-age=63072000; includeSubDomains")
    return response


app.include_router(auth.router)
app.include_router(stats.router)
app.include_router(documents.router)
app.include_router(records.router)
app.include_router(conflicts.router)
app.include_router(audit.audit_router)
app.include_router(audit.activity_router)
app.include_router(parcels.router)


@app.get("/api/health")
def health():
    return {"status": "ok"}